AmazonHelp: ecommerce
AppleSupport: electronics
Uber_Support: rideshare
SpotifyCares: streaming
Delta: flight
Tesco: retail
AmericanAir: flight
TMobileHelp: telecom
comcastcares: telecom_isp
British_Airways: flight
SouthwestAir: flight
VirginTrains: transit
Ask_Spectrum: telecom_isp
XboxSupport: gaming
sprintcare: telecom
hulu_support: streaming
sainsburys: retail
GWRHelp: transit
AskPlayStation: gaming
VerizonSupport: telecom
UPSHelp: logistics
ATVIAssist: gaming
O2: telecom
Safaricom_Care: telecom
idea_cares: telecom
AskTarget: retail
AirAsiaSupport: flight
BofA_Help: banking
SW_Help: transit
AdobeCare: software
AskeBay: ecommerce
sprintcare: telecom
AskPlayStation: gaming
ATVIAssist: gaming
AirAsiaSupport: flight
AskPayPal: fintech
116025: retail
115768: logistics
